---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.admin.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cookieSecret: {{ .Values.admin.secrets.cookieSecret | default (randAlphaNum 32) | b64enc }}
  apiKey: {{ .Values.admin.secrets.apiKey | default (randAlphaNum 32) | b64enc }}
