{{- if not .Values.secrets.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.api.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  database: {{ .Values.secrets.database.api.dbName | default "api" | b64enc }}
  jwtSecret: {{ .Values.secrets.api.jwtSecret | default (randAlphaNum 32) | b64enc }}
  fixedAuthTokens: {{ .Values.secrets.api.fixedAuthTokens | default (printf "[{\"token\":\"%s\",\"userId\":\"1\",\"authProvider\":\"openstad\"}]" (randAlphaNum 32)) | b64enc }}
  hashIpAddresses: {{ .Values.secrets.api.hashIpAddresses | default "false" | b64enc }}
  hashIpSalt: {{ .Values.secrets.api.hashIpSalt | default (randAlphaNum 16) | b64enc }}
{{- end -}}
