{{- if not .Values.secrets.database.existingDbSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.auth.databaseSecret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  database: {{ .Values.secrets.database.auth.dbName | default "auth" | b64enc }}
{{- end -}}
