---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.email.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  host: {{ .Values.secrets.mail.host | b64enc }}
  port: {{ .Values.secrets.mail.port | b64enc }}
  username: {{ .Values.secrets.mail.username | b64enc }}
  password: {{ .Values.secrets.mail.password | b64enc }}
  transporterType: {{ .Values.secrets.mail.transporterType | default "smtp" | b64enc }}
  msClientId: {{ .Values.secrets.mail.microsoft.clientId | default "" | b64enc }}
  msTenantId: {{ .Values.secrets.mail.microsoft.tenantId | default "" | b64enc }}
  msClientSecret: {{ .Values.secrets.mail.microsoft.clientSecret | default "" | b64enc}}
