---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.email.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  host: {{ .Values.secrets.mail.host | b64enc }}
  port: {{ .Values.secrets.mail.port | b64enc }}
  username: {{ .Values.secrets.mail.username | b64enc }}
  password: {{ .Values.secrets.mail.password | b64enc }}
