---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.image.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  verificationToken: {{ .Values.image.secrets.verificationToken | default (randAlphaNum 32) | b64enc }}
