{{- if not .Values.secrets.database.existingPasswordSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.passwordSecret.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  mysql-root-password: {{ .Values.secrets.database.rootPassword | default ( randAlphaNum 12 ) | b64enc }}
  mysql-replication-password: {{ .Values.secrets.database.replicationPassword | default ( randAlphaNum 12 ) | b64enc }}
  mysql-password: {{ .Values.secrets.database.password | default ( randAlphaNum 12 ) | b64enc }}
{{- end -}}
