{{- if not .Values.secrets.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.pdf.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  pdfApiEndpoint: {{ .Values.secrets.pdf.apiEndpoint | default "" | b64enc }}
  pdfApiKey: {{ .Values.secrets.pdf.apiKey | default "" | b64enc }}
{{- end -}}
