{{- if not .Values.secrets.s3.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.s3.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cmsEndpoint: {{ .Values.secrets.cms.s3.endpoint | default "" | b64enc }}
  cmsBucket: {{ .Values.secrets.cms.s3.bucket | default "" | b64enc }}
  cmsRegion: {{ .Values.secrets.cms.s3.region | default "" | b64enc }}
  cmsKey: {{ .Values.secrets.cms.s3.key | default "" | b64enc }}
  cmsSecret: {{ .Values.secrets.cms.s3.secret | default "" | b64enc }}
{{- end -}}
