---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-session-secret
  namespace: {{ .Release.Namespace }}
data:
  secret: {{ .Values.secrets.auth.sessionSecret | default ( randAlphaNum 12 ) | b64enc }}
