{{- if not .Values.secrets.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.session.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  secret: {{ .Values.secrets.auth.sessionSecret | default ( randAlphaNum 12 ) | b64enc }}
{{- end -}}
