export const FIELD_LABELS: Record<string, string> = {
  config: 'Configuratie',
  items: 'Vragen',
  title: 'Titel',
  description: 'Beschrijving',
  summary: 'Samenvatting',
  name: 'Naam',
  label: 'Label',
  color: 'Kleur',
  url: 'URL',
  email: 'E-mail',
  role: 'Rol',
  images: 'Afbeeldingen',
  location: 'Locatie',
  budget: 'Budget',
  modBreaks: 'Modbreaks',
  statuses: 'Statussen',
  tags: 'Tags',
  general: 'Algemeen',
  submit: 'Indienen',
  confirmation: 'Bevestiging',
  display: 'Weergave',
  publishDate: 'Publicatiedatum',
  startDate: 'Startdatum',
  extraData: 'Extra gegevens',
  widgetId: 'Widget ID',
  projectId: 'Project ID',
  fromAddress: 'Afzender e-mail',
  fromName: 'Afzendernaam',
  pdfAttachmentEnabled: 'PDF bijlage',
  pdfTitle: 'PDF titel',
  pdfDescription: 'PDF beschrijving',
  fieldKey: 'Veldnaam',
  fieldOptions: 'Antwoordopties',
  options: 'Antwoordopties',
  matrix: 'Matrix (rijen/kolommen)',
  questionType: 'Type antwoorden',
  type: 'Type',
  variant: 'Opmaak',
  placeholder: 'Placeholder',
  required: 'Verplicht',
  fieldRequired: 'Verplicht',
  requiredMessage: 'Foutmelding bij verplicht',
  minCharacters: 'Minimaal aantal tekens',
  maxCharacters: 'Maximaal aantal tekens',
  minValue: 'Minimumwaarde',
  maxValue: 'Maximumwaarde',
  defaultValue: 'Standaardwaarde',
  multiple: 'Meerdere toestaan',
  maxChoices: 'Maximaal te selecteren opties',
  maxChoicesMessage: 'Maximaal aantal bereikt melding',
  showSmileys: 'Smileys tonen',
  matrixMultiple: 'Meerdere antwoorden per rij',
  weights: 'Wegingen',
  numberingStyle: 'Nummering stijl',
  nextPageText: 'Tekst: Volgende pagina',
  prevPageText: 'Tekst: Vorige pagina',
  videoUrl: 'Video URL',
  onlyForModerator: 'Wie mag dit veld zien',
  fieldType: 'Weergave type',
  content: 'Inhoud',
  routingInitiallyHide: 'Verborgen bij routing',
  routingSelectedQuestion: 'Routing vraag',
  routingSelectedAnswer: 'Routing antwoord',
  labelA: 'Label voor A',
  labelB: 'Label voor B',
  sliderTitleUnderA: 'Uitleg bij A',
  sliderTitleUnderB: 'Uitleg bij B',
  skipQuestion: 'Vraag overslaan',
  skipQuestionLabel: 'Tekst bij overslaan',
  showMoreInfo: 'Extra info',
  moreInfoButton: 'Meer informatie knop tekst',
  moreInfoContent: 'Meer informatie tekst',
  view: 'Weergave',
  selectAll: 'Selecteer alles optie',
  selectAllLabel: 'Selecteer alles label',
  icon: 'Icoon',
  buttonText: 'Knoptekst',
  imageUrl: 'Afbeelding URL',
  openInNewTab: 'Openen in nieuw tabblad',
  displayPagination: 'Paginering tonen',
  displaySorting: 'Sorteeropties weergeven',
  displaySearchBar: 'Zoekbalk tonen',
  displaySearch: 'Zoekbalk tonen',
  displaySearchText: 'Zoektekst tonen',
  displayBanner: 'Titel boven overzicht weergeven',
  displayMap: 'Kaart weergeven',
  displayAsTabs: 'Als tabs weergeven',
  displayLocationFilter: 'Locatie filter weergeven',
  displayTitle: 'Titel weergeven',
  displayDescription: 'Beschrijving weergeven',
  displaySummary: 'Samenvatting weergeven',
  displayArguments: 'Aantal argumenten weergeven',
  displayVote: 'Aantal stemmen weergeven',
  displayStatusLabel: 'Status label weergeven',
  displayDocuments: 'Documenten weergeven',
  displayTags: 'Tags weergeven',
  displayUser: 'Gebruiker weergeven',
  displayCreatedAt: 'Aanmaakdatum weergeven',
  displayLikeButton: 'Like button weergeven',
  displayBudget: 'Budget weergeven',
  displaySocials: 'Social media opties weergeven',
  displayVariant: 'Weergave versie',
  displayCollapsibleFilter: 'Filter inklapbaar',
  displayTagIcon: 'Tag icoon weergeven',
  displayOverviewTagGroups: 'Tags in overzicht tonen',
  displayTagFilters: 'Tag filters tonen',
  displayTagGroupName: 'Tag groep naam tonen',
  displayRanking: 'Ranking weergeven',
  displayPriceLabel: 'Prijslabel weergeven',
  displayModBreak: 'Modbreak weergeven',
  clickableImage: 'Afbeelding klikbaar',
  displayDislike: 'Dislike button tonen',
  showProgressBar: 'Voortgangsbalk weergeven',
  showNewsletterButton: 'Nieuwsbrief knop tonen',
  showVoteCount: 'Aantal stemmen tonen',
  showOriginalResource: 'Originele inzending tonen',
  allowLikingInOverview: 'Stemmen in overzicht toestaan',
  hideCounters: 'Stemteller verbergen',
  autoApply: 'Filters automatisch toepassen',
  itemsPerPage: 'Items per pagina',
  defaultSorting: 'Standaard sortering',
  counterType: 'Type teller',
  headingLevel: 'Heading level',
  bannerText: 'Titel boven overzicht',
  applyText: 'Tekst voor filters toepassen',
  resetText: 'Tekst voor filters resetten',
  searchPlaceholder: 'Zoek placeholder',
  yesLabel: 'Label voor Ja',
  noLabel: 'Label voor Nee',
  progressBarDescription: 'Voortgangsbalk informatie',
  voteMessage: 'Stem bericht',
  thankMessage: 'Bedank bericht',
  notEnoughBudgetText: 'Onvoldoende budget tekst',
  step1Title: 'Stap 1 titel',
  step2Title: 'Stap 2 titel',
  step3Title: 'Stap 3 titel',
  panelTitle: 'Paneel titel',
  overviewTitle: 'Overzicht titel',
  resourceCardTitle: 'Inzending kaart titel',
  newsLetterTitle: 'Nieuwsbrief titel',
  newsLetterLink: 'Nieuwsbrief link',
  budgetChosenTitle: 'Gekozen budget titel',
  budgetRemainingTitle: 'Resterend budget titel',
  resourceListColumns: 'Aantal kolommen',
  onlyIncludeTagIds: 'Alleen deze tags',
  onlyIncludeStatusIds: 'Alleen deze statussen',
  voteType: 'Stem type',
  minBudget: 'Minimum budget',
  maxBudget: 'Maximum budget',
  minResources: 'Minimum inzendingen',
  maxResources: 'Maximum inzendingen',
  requiredUserFields: 'Verplichte gebruikersvelden',
  clustering: 'Clustering',
  markerHref: 'Marker link',
  categorize: 'Categoriseren',
  tilesVariant: 'Kaart stijl',
  groupByField: 'Groeperen op',
  sentiment: 'Sentiment',
  emptyListText: 'Tekst bij lege lijst',
  formIntro: 'Formulier introductie',
  isReplyingEnabled: 'Reageren toestaan',
  isSentimentEnabled: 'Sentiment inschakelen',
  isVotingEnabled: 'Stemmen op reacties inschakelen',
  requiredFields: 'Verplichte velden',
  documentsTitle: 'Documenten titel',
  documentsDesc: 'Documenten beschrijving',
  commentsVotingEnabled: 'Stemmen op reacties',
  shareChannels: 'Deel kanalen',
};

const QUESTION_TYPES: Record<string, string> = {
  open: 'Open vraag',
  multiplechoice: 'Enkele keuze',
  multiple: 'Meerkeuze',
  checkbox: 'Meerkeuze',
  radiobox: 'Enkele keuze',
  select: 'Dropdown',
  text: 'Tekstveld',
  matrix: 'Matrix',
  scale: 'Schaal',
  images: 'Afbeeldingen',
  imageUpload: 'Afbeelding upload',
  documentUpload: 'Document upload',
  map: 'Locatie',
  pagination: 'Paginering',
  sort: 'Sorteren',
  video: 'Video',
  swipe: 'Swipe',
  dilemma: 'Dilemma',
  'a-b-slider': 'Van A naar B slider',
  none: 'Informatie blok',
  information: 'Informatie blok',
  title: 'Titel',
  summary: 'Samenvatting',
  description: 'Beschrijving',
  tags: 'Tags',
  location: 'Locatie',
  estimate: 'Geschatte kosten',
  role: 'Rol',
  phone: 'Telefoonnummer',
  advice: 'Tips',
  budget: 'Budget',
};

export const VALUE_LABELS: Record<string, Record<string, string>> = {
  onlyForModerator: { true: 'Alleen admin', false: 'Iedereen' },
  routingInitiallyHide: { true: 'Nee (verborgen)', false: 'Ja (zichtbaar)' },
  mobileCase: { true: 'Nee', false: 'Ja' },
  variant: {
    'text input': '1 regel',
    textarea: 'Tekstvak',
    'micro-score': 'Icons met score',
    small: 'Compact',
    medium: 'Standaard',
    large: 'Groot',
  },
  display: { simple: 'Simpel', full: 'Volledig' },
  submissionField: { resourceType: 'Resource type', theme: 'Thema' },
  tilesVariant: {
    NLMaps: 'NLMaps',
    Amsterdam: 'Amsterdam',
    OpenStreetMaps: 'OpenStreetMaps',
    advanced: 'Geavanceerd',
  },
  zoom: { none: 'Niet', markers: 'Op markers', area: 'Op gebied' },
  mapIcon: {
    select: 'Selecteert een resource',
    details: 'Toon resource details',
  },
  displayType: {
    cardrow: 'Inzending op nieuwe pagina',
    cardgrid: 'Inzendingen in dialog',
    raw: 'Eigen template',
  },
  counterType: {
    resource: 'Inzendingen',
    vote: 'Stemmen',
    votedUsers: 'Stemmers',
    argument: 'Reacties',
    submission: 'Formulier inzendingen',
  },
  questionType: QUESTION_TYPES,
  type: QUESTION_TYPES,
};

const HIDDEN_ITEM_FIELDS = new Set([
  'trigger',
  'key',
  'key1',
  'key2',
  'key_b',
  'text1',
  'text2',
  'image1',
  'image2',
  'image_b',
  'imageAlt',
  'imageDescription',
  'infoField',
  'infofieldExplanation',
  'explanationRequired',
  'hideLabel',
  'createImageSlider',
  'imageClickable',
  'randomizeItems',
  'tags',
]);

export function getItemDisplayFields(item: any): string[] {
  if (!item || typeof item !== 'object') return [];
  return Object.keys(item).filter((k) => !HIDDEN_ITEM_FIELDS.has(k));
}
