export const WIDGET_FIELD_LABELS: Record<string, Record<string, string>> = {
  account: {
    allowNickname: 'Gebruikersnaam toestaan',
    allowUserEdit: 'Bewerken toestaan',
    info_description: 'Persoonlijke gegevens beschrijving',
    info_title: 'Persoonlijke gegevens titel',
    loginButtonText: 'Tekst voor de inlogknop',
    loginRequiredText: 'Tekst die getoond wordt boven de inlogknop',
    overview_description: 'Overzicht beschrijving',
    overview_title: 'Overzicht titel',
    showEmailConsentField: 'Toon veld voor e-mail toestemming',
    showLogoutButton: 'Toon uitlogknop',
    user_description: 'Gebruikersnaam beschrijving',
    user_title: 'Gebruikersnaam titel',
  },
  activity: {
    currentTitle: 'Titel voor huidige site',
    noActivityTextCurrent:
      'Tekst wanneer er geen activiteit op de huidige site is geweest',
    noActivityTextOther:
      'Tekst wanneer er geen activiteit op andere sites is geweest',
    otherTitle: 'Titel voor externe sites',
  },
  agenda: {
    defaultClosedFromBreakpoint:
      'Breekpunt vanaf wanneer de inhoud standaard ingeklapt wordt weergegeven',
    displayTitle: 'Titel weergeven',
    displayToggle: 'Toon een knop om de inhoud in/uit te klappen',
    title: 'Titel',
    toggleDefaultClosed: 'Standaard ingeklapt weergeven?',
    toggleEnd: 'Tot welk agenda-item moet de accordion lopen',
    toggleHideText: 'Tekst voor de knop om de inhoud te verbergen',
    toggleShowText: 'Tekst voor de knop om de inhoud te tonen',
    toggleStart: 'Vanaf welk agenda-item moet de accordion beginnen',
    toggleType: 'Type inklapbare inhoud',
    useActiveDates: 'Actief op basis van datum',
  },
  begrootmodule: {
    budgetChosenTitle: "'Gekozen' tekst",
    budgetRemainingTitle: "'Nog over' tekst",
    defaultSorting: 'Standaard manier van sorteren',
    displayModBreak: 'Toon de ModBreak',
    displayPagination: 'Paginering tonen',
    displayPriceLabel: 'Weergeef het prijslabel',
    displayRanking: 'Weergeef de volgorde',
    displaySearch: 'Zoekveld weergeven',
    displaySearchText: 'Zoektekst weergeven',
    displaySorting: 'Sorteeropties weergeven',
    displayTagFilters: 'Filteren op tags weergeven?',
    filterBehavior: 'Kies de manier waarop je de filters wilt combineren',
    hideReadMore: "Verberg de 'lees meer' knop bij de inzendingen?",
    hideTagsForResources: 'Verberg tags bij de inzendingen',
    itemsPerPage: 'Hoeveelheid items per pagina',
    newsLetterLink: 'Nieuws brief link',
    newsLetterTitle: 'Nieuws brief titel tekst',
    notEnoughBudgetText: 'Onbeschikbare buttons',
    onlyIncludeStatusIds:
      'Geef enkel de inzendingen met de volgende status weer:',
    onlyIncludeTagIds: 'Geef enkel de resources met de volgende tags weer:',
    originalResourceText: 'Tekst voor de link (optioneel)',
    originalResourceUrl: 'URL van de oorspronkelijke inzending',
    overviewTitle: 'Titel boven het overzicht van alle inzendingen',
    panelTitle: 'Titel',
    resourceCardTitle: 'Titel inzendingen kaart',
    resourceListColumns: 'Inzendingslijst',
    scrollWhenMaxReached: 'Forceer een scroll',
    showConfetti: 'Toon confetti na het stemmen',
    showInfoMenu: 'Weergeef teller met informatie',
    showNewsletterButton:
      'Wordt de nieuwsbrief knop weergegeven na het stemmen?',
    showOriginalResource: 'Weergeef de URL van de originele inzending',
    showVoteCount: 'Weergeef de hoeveelheid stemmen',
    sorting: 'Selecteer uw gewenste sorteeropties',
    stemCodeTitle: 'Stemcode knop tekst 1',
    stemCodeTitleSuccess: 'Stemcode knop tekst 2',
    step0: 'Stap 0: Stemmen / budget per thema intro',
    step1: 'Stap 1: Intro',
    step1Add: "Tekst voor de knop 'Voeg toe'",
    step1Delete: "Tekst voor de knop 'Verwijder'",
    step1MaxText:
      'Tekst wanneer het maximaal aantal om te selecteren is bereikt',
    step1Tab: 'Tab 1 titel',
    step1Title: 'Titel',
    step2: 'Stap 2: Intro',
    step2Tab: 'Tab 2 titel',
    step2Title: 'Titel',
    step3: 'Stap 3: Intro',
    step3Tab: 'Tab 3 titel',
    step3Title: 'Titel boven de uitleg',
    step3success: 'Succesvolle authenticatie',
    step4Tab: 'Tab 4 titel',
    tagGroups: 'Selecteer de gewenste tag groepen',
    tagTypeSelector:
      'Selecteer de manier waarop er geselecteerd / gebudgetteerd moet worden',
    tagTypeTag: 'Selecteer meerdere taggroepen om te gebruiken',
    tagTypeTagGroup: 'Selecteer welke taggroepen gebruikt worden',
    textActiveSearch: 'Tekst voor actieve resultaten',
    thankMessage: 'Bedankt bericht',
    voteAfterLoggingIn: 'Automatisch stemmen na inloggen?',
    voteMessage: 'Succesvol gestemd bericht',
  },
  choiceguide: {
    afterUrl: 'URL van de resultaat pagina',
    beforeUrl: 'URL van de inleidende pagina',
    choicesInBetweenPreferenceTitle:
      'Titel boven de keuzes, tussen twee voorkeuren in',
    choicesNoPreferenceYetTitle: 'Titel boven de keuzes, nog geen voorkeur',
    choicesPreferenceMaxColor: 'Kleur van de balken, maximaal',
    choicesPreferenceMinColor: 'Kleur van de balken, minimaal',
    choicesPreferenceTitle: 'Titel boven de keuzes, met voorkeur',
    choicesType: 'Weergave van de voorkeuren',
    createImageSlider: 'Wil je van de afbeeldingen een slider maken?',
    defaultValue: 'Standaard aangevinkt?',
    description: 'Beschrijving',
    explanationA: 'Label onder slider A',
    explanationB: 'Label onder slider B',
    fieldRequired: 'Is dit veld verplicht?',
    hideLabel: 'Titel verbergen?',
    imageAlt: 'Afbeelding beschrijving voor screenreaders',
    imageAspectRatio: 'Weergave: afbeeldingen aspect ratio',
    imageClickable:
      'Moeten de afbeeldingen uitvergroot worden als erop geklikt wordt?',
    imageDescription: 'Beschrijving afbeelding',
    introDescription: 'Beschrijving inleiding',
    introTitle: 'Titel inleiding',
    isOtherOption: "Is 'Anders, namelijk...'",
    key: 'Optie tekst',
    labelA: 'Label voor A',
    labelB: 'Label voor B',
    loginRequired: 'Login vereist',
    loginText: 'Login tekst',
    loginTextButton: 'Login tekst knop',
    matrixMultiple: 'Mogen er meerdere antwoorden per rij worden geselecteerd?',
    maxCharacters: 'Maximaal aantal tekens',
    maxCharactersError: 'Foutmelding voor maximaal aantal karakters',
    maxCharactersOverWarning:
      'Waarschuwing bij overschrijden maximaal aantal karakters',
    maxCharactersWarning: 'Waarschuwing voor maximaal aantal karakters',
    maxChoices: 'Maximaal te selecteren opties',
    maxChoicesMessage: 'Maximaal aantal bereikt melding',
    maxUploadSizeMB: 'Maximale uploadgrootte (MB)',
    minCharacters: 'Minimaal aantal tekens',
    minCharactersError: 'Foutmelding voor minimaal aantal karakters',
    minCharactersWarning: 'Waarschuwing voor minimaal aantal karakters',
    moreInfoButton: 'Meer informatie knop tekst',
    moreInfoContent: 'Meer informatie tekst',
    multiple: 'Mogen er meerdere tegelijkertijd geüpload worden?',
    nextButtonText: 'Volgende vraag tekst',
    nextPageText: 'Tekst voor: Volgende pagina',
    placeholder: 'Placeholder',
    prevPageText: 'Tekst voor: Vorige pagina',
    routingInitiallyHide: 'Is deze vraag altijd zichtbaar?',
    routingSelectedQuestion:
      'Welke vraag beïnvloedt de zichtbaarheid van deze vraag?',
    showBackButtonInTopOfPage: "Toon de 'Vorige' knop bovenaan de pagina?",
    showMinMaxAfterBlur: 'Toon min/max waarschuwing na verlaten van het veld',
    showMoreInfo: 'Extra info',
    showPageCountAndCurrentPageInButton:
      "Wil je de voortgang van de pagina's te zien is in de 'Volgende' knop?",
    skipQuestion: 'Mogelijkheid om deze vraag over te slaan?',
    skipQuestionAllowExplanation:
      'Mogelijkheid voor de gebruiker om toelichting te geven voor het overslaan?',
    skipQuestionExplanation: 'Titel boven het tekstveld van de toelichting',
    skipQuestionLabel: 'Tekst bij de checkbox voor het overslaan',
    sliderTitleUnderA: 'Uitleg bij A',
    sliderTitleUnderB: 'Uitleg bij B',
    stickyBarAtTop:
      'Moet de balk met de voortgang van de keuzewijzer bovenaan getoond worden?',
    stickyBarDefaultOpen:
      'Moet de balk met de voortgang van de keuzewijzer standaard geopend zijn?',
    submitButtonText: 'Verstuur knop tekst',
    title: 'Titel',
    type: 'Type antwoorden',
    variant: 'Is het veld qua grootte 1 regel of een tekstvak?',
  },
  choiceguideResults: {
    choiceguideWidgetId:
      'Van welke keuzewijzer moeten de resultaten getoond worden?',
    displayAsFeaturedOnly:
      'Moet de content van de topkeuze onder de resultaten als uitslag worden weergegeven?',
    displayDescription:
      'Beschrijving van de keuzeoptie tonen in het scoreblok?',
    displayImage: 'Afbeelding van de keuzeoptie tonen in het scoreblok?',
    displayTitle: 'Titel van de keuzeoptie tonen in het scoreblok?',
    hideScores: 'Scoreblok verbergen zodat alleen de uitslag wordt getoond',
  },
  comments: {
    autoApply:
      'Automatisch toepassen van de filters wanneer een filter wijzigt',
    closedText:
      'Welke tekst wil je tonen wanneer het niet meer mogelijk is om te reageren?',
    confirmation:
      'Krijgt de inzender van de gekoppelde inzending een mail bij een reactie?',
    confirmationReplies:
      'Krijgt de inzender van een reactie een mail bij een reactie op zijn/haar reactie?',
    defaultSorting: 'Standaard manier van sorteren',
    defaultTags: 'Selecteer de standaard tags',
    displayCollapsibleFilter: 'Filter inklapbaar maken',
    displayPagination: 'Paginering tonen',
    displaySearchBar: 'Zoekbalk tonen',
    emptyListText: 'Placeholder',
    extraFieldsTagGroups: 'Selecteer de gewenste tag groepen',
    extraReplyButton: 'Extra reageer knop',
    formIntro: 'Formulier intro',
    includeOrExclude: 'Toon reacties gekoppeld aan onderstaande tags',
    itemsPerPage: 'Hoeveelheid items per pagina',
    loginText: 'Placeholder tekst',
    onlyIncludeOrExcludeTagIds:
      'Geef enkel de resources met de volgende tags weer:',
    overwriteEmailAddress:
      'Overschrijf het e-mailadres voor de mail naar de inzender van de inzending',
    placeholder: 'Placeholder tekst',
    resourceId: 'Koppel aan een specifieke inzending',
    sentiment: 'Sentiment',
    sorting: 'Selecteer uw gewenste sorteeropties',
    title: 'Titel',
    useSentiments: 'Tonen van reacties:',
    variant: 'Variant type',
  },
  counter: {
    amount: 'Hoeveelheid',
    counterType: 'Type teller',
    includeOrExclude: 'Toon reacties gekoppeld aan onderstaande tags',
    label: 'Label',
    onlyIncludeOrExcludeTagIds:
      'Geef enkel de resources met de volgende tags weer:',
    opinion: 'Mening',
    resourceId: 'Koppel aan een specifieke inzending',
    rigCounter: 'Pas de teller aan',
    url: 'Url',
    widgetToFetchId: 'Gewenste keuzewijzer',
  },
  datecountdownbar: {
    afterText: 'Tekst rechts van de dagen kaart(en)',
    beforeText: 'Tekst links van de dagen kaart(en)',
    date: 'Einddatum',
    direction: 'Selecteer weergave',
    showHours: 'Toon uren',
    showLabels: 'Toon labels',
    showMinutes: 'Toon minuten',
  },
  distributionmodule: {
    afterSubmitUrl: 'Url voor redirecten na opslaan (optioneel)',
    appendText: 'Tekst na het verdeelde aantal',
    budgetErrorMessage: 'Geen geld meer foutmelding tekst',
    budgetErrorTitle: 'Geen geld meer foutmelding titel',
    budgetLeftoverText: 'Overig bedrag tekst',
    budgetTotalText: 'Totaal bedrag tekst',
    choice: 'Kies welk type er wordt gebruikt voor het verdelen',
    description: 'Beschrijving',
    formVisibility: 'Voor wie is de module zichtbaar?',
    placeholder: 'Placeholder',
    pointsErrorMessage: 'Geen punten meer foutmelding tekst',
    pointsErrorTitle: 'Geen punten meer foutmelding titel',
    pointsLeftoverText: 'Overige punten tekst',
    pointsTotalText: 'Totaal punten tekst',
    prependText: 'Tekst voor het verdeelde aantal',
    showProgress: 'Progressiebalk tonen?',
    title: 'Titel/Vraag',
    total: 'Aantal om te verdelen',
  },
  documentmap: {
    accessibilityUrl: 'Link naar pagina met begeleidende tekst',
    accessibilityUrlText: 'Tekst van de link',
    accessibilityUrlVisible: 'Heeft een pagina met begeleidende tekst?',
    addCommentText:
      'Als de gebruiker een reactie kan toevoegen, wat is de tekst die boven het veld staat?',
    addMarkerText:
      'Wat is de tekst in de knop voor het insturen van een reactie?',
    backUrlContent: 'Terug naar definitieve versie, begeleidende tekst',
    backUrlText: 'Terug naar definitieve versie, link tekst',
    closedText:
      'Welke tekst wil je tonen wanneer het niet meer mogelijk is om te reageren?',
    defaultSorting: 'Standaard manier van sorteren',
    defaultTags: 'Selecteer de standaard tags',
    definitiveUrl: 'Link naar pagina van de definitieve versie',
    definitiveUrlText: 'Tekst van de link',
    definitiveUrlVisible: 'Heeft een definitieve versie van het plan?',
    displayLikes: 'Toon de likes widget',
    displayMapSide: 'Aan welke kant wil je de map tonen?',
    displayPagination: 'Paginering tonen',
    displayResourceDescription: 'Wil je de beschrijving van de resource tonen?',
    displayResourceInfo: 'Aan welke kant wil je de info van de resource tonen?',
    displayResourceSummary: 'Wil je de samenvatting van de resource tonen?',
    displayResourceTitle: 'Wil je de titel van de resource tonen?',
    displaySearchBar: 'Zoekbalk tonen',
    emptyListText:
      'Wat is de tekst bij het reactie overzicht wanneer er nog geen reacties zijn?',
    entireDocumentVisible:
      'Welk gedeelte van de afbeelding moet zichtbaar zijn als de widget is ingeladen?',
    extraFieldsTagGroups: 'Selecteer de gewenste tag groepen',
    filterBehavior: 'Kies de manier waarop je de filters wilt combineren',
    hideCommentsList: 'Reactielijst verbergen',
    hideFilters: 'Filter-, zoek- en sorteeropties verbergen',
    hideToggleMarkers: 'Markers aan/uit-knop verbergen',
    includeOrExclude: 'Toon reacties gekoppeld aan onderstaande tags',
    infoPopupButtonText:
      'Wat is de tekst voor de knop die de info pop-up opent?',
    infoPopupContent: 'Wat is de helptekst die in de info pop-up staat?',
    itemsPerPage: 'Hoeveelheid items per pagina',
    largeDoc: 'Grotere weergave voor het document',
    loginText:
      'Wat is de tekst bij het reactie overzicht wanneer je niet bent ingelogd?',
    markerClickBehavior: 'Gedrag bij klikken op een marker',
    maxCharactersError: 'Foutmelding voor maximaal aantal karakters',
    maxCharactersWarning: 'Waarschuwing voor maximaal aantal karakters',
    maxZoom: 'Maximale zoomniveau voor inzoomen',
    minCharactersError: 'Foutmelding voor minimaal aantal karakters',
    minCharactersWarning: 'Waarschuwing voor minimaal aantal karakters',
    minZoom: 'Maximale zoomniveau voor uitzoomen',
    onlyAllowClickOnImage: 'Alleen markers op de afbeelding toelaten?',
    onlyIncludeOrExcludeTagIds:
      'Geef enkel de resources met de volgende tags weer:',
    openInfoPopupOnInit:
      'Wil je dat de info pop-up standaard open staat wanneer de widget wordt ingeladen?',
    popupNotLoggedInButton:
      'Welke tekst heeft de knop in de pop-up wanneer je niet bent ingelogd?',
    popupNotLoggedInText:
      'Welke tekst staat in de pop-up wanneer je niet bent ingelogd?',
    relativePathPrepend: 'Relatief pad naar document',
    resourceId: 'Koppel aan een specifieke inzending',
    resourceIdRelativePath: 'Geen specifieke inzending gekoppeld?',
    sorting: 'Selecteer uw gewenste sorteeropties',
    statusId: 'Definitieve status',
    submitCommentText:
      'Wat is de tekst in de knop voor het insturen van een reactie?',
    tagGroups: 'Selecteer de gewenste tag groepen',
  },
  enquete: {
    afterSubmitUrl: 'Url voor redirecten na opslaan (optioneel)',
    confirmationAdmin:
      'Krijgt de beheerder een bevestiging per mail bij een nieuwe inzending?',
    confirmationUser:
      'Krijgt de gebruiker een bevestiging per mail van zijn inzending?',
    createImageSlider: 'Wil je van de afbeeldingen een slider maken?',
    defaultValue: 'Standaard aangevinkt?',
    description: 'Beschrijving',
    description_b: 'Beschrijving',
    displayDescription: 'Enquête beschrijving weergeven',
    displayTitle: 'Enquête titel weergeven',
    draftRetentionHours: 'Bewaartijd concept (uren)',
    enableDraftPersistence: 'Concept automatisch opslaan',
    explanationRequired: 'Toelichting vragen',
    fieldKey: 'Key voor het opslaan',
    fieldRequired: 'Is dit veld verplicht?',
    formStyle: 'Visuele stijl van het formulier',
    formVisibility: 'Voor wie is de enquête zichtbaar?',
    hideLabel: 'Titel verbergen?',
    imageAlt: 'Afbeelding beschrijving voor screenreaders',
    imageClickable:
      'Moeten de afbeeldingen uitvergroot worden als erop geklikt wordt?',
    imageDescription: 'Beschrijving afbeelding',
    infoBlockExtraButton: 'Link',
    infoBlockExtraButtonTitle: 'Titel',
    infoBlockShareButton: "Toon 'Deel' knop?",
    infoBlockStyle: 'Informatie blok stijl',
    infoField: 'Extra info veld',
    isOtherOption: "Is 'Anders, namelijk...'",
    key: 'Optie tekst',
    key_b: 'Titel',
    matrixMultiple: 'Mogen er meerdere antwoorden per rij worden geselecteerd?',
    maxCharacters: 'Maximaal aantal tekens',
    maxCharactersError: 'Foutmelding voor maximaal aantal karakters',
    maxCharactersOverWarning:
      'Waarschuwing bij overschrijden maximaal aantal karakters',
    maxCharactersWarning: 'Waarschuwing voor maximaal aantal karakters',
    maxChoices: 'Maximaal te selecteren opties',
    maxChoicesMessage: 'Maximaal aantal bereikt melding',
    maxUploadSizeMB: 'Maximale uploadgrootte (MB)',
    minCharacters: 'Minimaal aantal tekens',
    minCharactersError: 'Foutmelding voor minimaal aantal karakters',
    minCharactersWarning: 'Waarschuwing voor minimaal aantal karakters',
    multiple: 'Mogen er meerdere tegelijkertijd geüpload worden?',
    nextPageText: 'Tekst voor: Volgende pagina',
    numberingStyle: 'Nummeringstijl',
    overwriteEmailAddress:
      'Overschrijf het e-mailadres waar de bevesting naartoe wordt gestuurd',
    placeholder: 'Placeholder',
    prevPageText: 'Tekst voor: Vorige pagina',
    questionType: 'Type antwoorden',
    randomizeItems: 'Willekeurige volgorde',
    routingInitiallyHide: 'Is deze vraag altijd zichtbaar?',
    routingSelectedQuestion:
      'Welke vraag beïnvloedt de zichtbaarheid van deze vraag?',
    showMinMaxAfterBlur: 'Toon min/max waarschuwing na verlaten van het veld',
    showSmileys: 'Wil je smileys tonen in plaats van een schaal?',
    title: 'Titel/Vraag',
    userEmailAddress:
      'Welk veld moet er worden gebruikt voor de bevestiging naar de gebruiker',
    variant: 'Type open vraag',
    videoLang: 'Ondertiteling taal',
    videoSubtitle: 'Ondertiteling',
    videoUrl: 'Video url',
  },
  likes: {
    displayDislike: 'Wil je de dislike button tonen?',
    hideCounters: 'Moet het aantal stemmen verborgen worden?',
    noLabel: 'Label voor "Nee"',
    progressBarDescription: 'Voortgang balk informatie',
    resourceId: 'Koppel aan een specifieke inzending',
    showConfetti: 'Toon confetti bij liken',
    showProgressBar: 'Voortgang balk weergeven',
    title: 'Titel',
    variant: 'Variant type',
    yesLabel: 'Label voor "Ja"',
  },
  map: {
    aspectRatio: 'Aspect ratio',
    clickingChoosesLocation: 'Op de kaart klikken selecteert een locatie?',
    clustering: 'Clustering actief?',
    clusteringSensitivity: 'Gevoeligheid van clustering',
    color: 'Kleur',
    defaultImage: 'Default afbeelding',
    defaultLocation: 'Default Location icon',
    defaultSorting: 'Selecteer de standaard manier van sorteren.',
    display: 'Weergave',
    displayReactions: 'Weergave',
    displayShare: 'Worden de socialmedia deelknoppen weergegeven?',
    filterLabel: 'Label voor type in filters',
    icon: 'Icoon',
    idNonActiveReactions:
      'IDs van resources waar reacties niet actief voor zijn.',
    label: 'Label',
    link: 'Link naar gebruikerspagina',
    mapIcon: 'Op een kaart icon klikken:',
    markerInteractionType: 'Hoe wil je dat de interactie werkt met de markers?',
    mobileCase: 'Opent op mobiel de lijst van resources over de kaart heen?',
    mobilePreviewLoggedInHTML: 'mobilePreviewLoggedInHTML',
    mobilePreviewNotLoggedInHTML: 'mobilePreviewNotLoggedInHTML',
    multipleImages: 'Meerdere afbeeldingen bij één resource?',
    name: 'Naam van het resource',
    noSelectionLoggedInHTML: 'noSelectionLoggedInHTML',
    noSelectionNotLoggedInHTML: 'noSelectionNotLoggedInHTML',
    reactionsAvailable: 'Reacties staan...',
    searchLocations: 'Waar wordt in gezocht?',
    selectableOptions: 'Selecteer uw gewenste deelopties',
    selectionActiveLoggedInHTML: 'selectionActiveLoggedInHTML',
    selectionActiveNotLoggedInHTML: 'selectionActiveNotLoggedInHTML',
    selectionInactiveLoggedInHTML: 'selectionInactiveLoggedInHTML',
    selectionInactiveNotLoggedInHTML: 'selectionInactiveNotLoggedInHTML',
    showNoSelectionBlock: 'Weergave',
    sorting: 'Selecteer uw gewenste sorteeropties',
    submissionField: 'Type inzending',
    template: 'Metadata regel template',
    textAboveInput: 'Tekst boven inputveld',
    textEmptyInput: 'Tekst in lege inputveld',
    title: 'Titel boven de reacties',
    variant: 'Variant',
    zoom: 'Zoom en center',
  },
  multiprojectresourceoverview: {
    detailPageLink: 'Link naar detailpagina van inzending',
    excludeResourcesInOverview: 'Toon geen inzendingen in het overzicht',
    includeProjectsInOverview:
      'Toon dit project zelf als tegel in het overzicht',
    label: 'Label in overzicht',
    overviewDescription: 'Beschrijving van het project',
    overviewSummary: 'Korte samenvatting van het project',
    overviewTitle: 'Titel van de project tegel',
    overviewUrl: 'Link waar de project tegel naartoe leidt',
    projectLat: 'Latitude voor project marker',
    projectLng: 'Longitude voor project marker',
  },
  rawresource: {
    rawInput: 'Template',
    resourceId: 'Resource',
    resourceIdRelativePath: 'Geen specifieke inzending gekoppeld?',
  },
  resourcedetail: {
    backUrlIdRelativePath: 'Relatief pad naar document',
    backUrlText: 'Tekst van de terug knop',
    clickableImage: 'Moet de afbeelding in de dialog klikbaar zijn?',
    displayBudget: 'Budget weergeven',
    displayBudgetDocuments: 'Budget bestanden weergeven',
    displayDate: 'Publicatiedatum weergeven',
    displayDeleteButton: 'Toon de knop om de inzending te verwijderen',
    displayDeleteEditButtonOnTop:
      'Toon de bewerk- en verwijderknoppen bovenaan in plaats van onderaan',
    displayDescription: 'Beschrijving weergeven',
    displayDescriptionExpandable: 'Uitklapbaar',
    displayDescriptionExpandable_expandAfterText:
      "Tekst voor de 'Lees minder' knop",
    displayDescriptionExpandable_expandBeforeText:
      "Tekst voor de 'Lees meer' knop",
    displayDescriptionExpandable_visibleLines:
      'Aantal zichtbare regels (0 - 10)',
    displayDocuments: 'Geüploade documenten weergeven',
    displayEditResourceButton: 'Toon de knop om de inzending te bewerken',
    displayImage: 'Afbeelding weergeven',
    displayImageDescription: 'Beschrijving van de afbeelding tonen',
    displayLikes: 'Toon de likes widget',
    displayLocation: 'Plaats weergeven',
    displaySocials: 'Delen via social media opties weergeven',
    displayStatus: 'Gekoppelde statussen weergeven',
    displayStatusBar: 'De balk met statussen weergeven bij de afbeelding?',
    displaySummary: 'Samenvatting weergeven',
    displayTags: 'Gekoppelde tags weergeven',
    displayTimeline: 'Tijdlijn weergeven',
    displayTitle: 'Titel weergeven',
    displayUser: 'Gebruiker weergeven',
    documentsDesc:
      'Welke beschrijving moet er boven de download knop(pen) komen?',
    documentsTitle: 'Welke titel moet er boven de download knop(pen) komen?',
    pageTitle: 'Inzending titel gebruiken als pagina titel',
    resourceId: 'Koppel aan een specifieke inzending',
    resourceIdRelativePath: 'Geen specifieke inzending gekoppeld?',
    selectedSocialShareOptions: 'Gedeelde social media opties',
    urlWithResourceFormForEditing:
      'Wat is de URL van de pagina waar het formulier staat?',
  },
  resourcedetailmap: {
    resourceId: 'Koppel aan een specifieke inzending',
  },
  resourcedetailwithmap: {
    backUrl: 'Overzicht url:',
    displayBudget: 'Budget weergeven',
    displayBudgetDocuments: 'Budget bestanden weergeven',
    displayDate: 'Publicatiedatum weergeven',
    displayDescription: 'Beschrijving weergeven',
    displayImage: 'Afbeelding weergeven',
    displayLikes: 'Toon de likes widget',
    displayLocation: 'Plaats weergeven',
    displaySocials: 'Delen via social media opties weergeven',
    displayStatus: 'Gekoppelde statussen weergeven',
    displaySummary: 'Samenvatting weergeven',
    displayTags: 'Gekoppelde tags weergeven',
    displayTitle: 'Titel weergeven',
    displayUser: 'Gebruiker weergeven',
    resourceId: 'Koppel aan een specifieke inzending',
    resourceIdRelativePath: 'Geen specifieke inzending gekoppeld?',
  },
  resourceform: {
    allowAnonymousSubmissions: 'Mogen niet‑ingelogde gebruikers inzenden?',
    confirmationAdmin:
      'Krijgt de beheerder een bevestiging per mail bij een nieuwe inzending?',
    confirmationUser:
      'Krijgt de gebruiker een bevestiging per mail van zijn inzending?',
    defaultValue: 'Standaard aangevinkt?',
    description: 'Beschrijving',
    fieldKey: 'Key voor het opslaan',
    fieldType: 'Hoe wil je de tags weergeven in het formulier?',
    formName: 'Naam formulier',
    hideAdmin:
      'Wordt de admin verborgen van het project na de eerste publieke actie?',
    isOtherOption: "Is 'Anders, namelijk...'",
    key: 'Optie tekst',
    loginButtonText: 'Login knoptekst',
    loginText: 'Login tekst',
    matrixMultiple: 'Mogen er meerdere antwoorden per rij worden geselecteerd?',
    maxCharacters: 'Maximaal aantal tekens',
    maxCharactersError: 'Foutmelding voor maximaal aantal karakters',
    maxCharactersOverWarning:
      'Waarschuwing bij overschrijden maximaal aantal karakters',
    maxCharactersWarning: 'Waarschuwing voor maximaal aantal karakters',
    maxChoices: 'Maximaal te selecteren opties',
    maxChoicesMessage: 'Maximaal aantal bereikt melding',
    maxUploadSizeMB: 'Maximale uploadgrootte (MB)',
    minCharacters: 'Minimaal aantal tekens',
    minCharactersError: 'Foutmelding voor minimaal aantal karakters',
    minCharactersWarning: 'Waarschuwing voor minimaal aantal karakters',
    multiple: 'Mogen er meerdere tegelijkertijd geüpload worden?',
    nameInHeader:
      'Wordt de gebruikersnaam weergegeven in de header van het formulier?',
    nextPageText: 'Tekst voor: Volgende pagina',
    onlyForModerator: 'Wie mag de ingevulde waarde van dit veld zien?',
    placeholder: 'Placeholder',
    prevPageText: 'Tekst voor: Vorige pagina',
    redirectUrl:
      'Naar welke URL moet de gebruiker geleid worden na het invullen van het formulier?',
    resource: 'Soort inzending (vanuit de configuratie)',
    routingInitiallyHide: 'Is deze vraag altijd zichtbaar?',
    routingSelectedQuestion:
      'Welke vraag beïnvloedt de zichtbaarheid van deze vraag?',
    saveButton: 'Tekst voor de opslaan-knop',
    selectAll: "Voeg een 'Selecteer alles' optie toe?",
    selectAllLabel: "Label voor de 'Selecteer alles' optie",
    showMinMaxAfterBlur: 'Toon min/max waarschuwing na verlaten van het veld',
    submitButton: 'Tekst voor de oplever-knop',
    title: 'Titel/Vraag',
    type: 'Type antwoorden',
    variant: 'Welke opmaak krijgt het tekstveld?',
  },
  resourceoverview: {
    allowLikingInOverview: 'Stemmen toestaan in het overzicht',
    applyText: 'Tekst voor het toepassen van de filters',
    autoApply:
      'Automatisch toepassen van de filters wanneer een filter wijzigt',
    bannerText: 'Titel boven het overzicht',
    clickableImage: 'Moet de afbeelding in de dialog klikbaar zijn?',
    closeFiltersOnAutoApply: 'Filtermenu sluiten na toepassen',
    defaultSorting: 'Standaard manier van sorteren',
    descriptionMaxLength:
      'Hoeveelheid karakters van de beschrijving die getoond wordt',
    dialogTagGroups:
      'Selecteer van welke tag groepen de tags getoond moeten worden in de dialog',
    displayArguments: 'Hoeveelheid aan argumenten weergeven',
    displayAsTabs: 'Moet de kaart en de lijst als tabs worden weergegeven?',
    displayBanner: 'Titel boven het overzicht weergeven?',
    displayBudget: 'Budget in dialog weergeven',
    displayCollapsibleFilter: 'Filter inklapbaar maken',
    displayCreatedAt: 'Aanmaakdatum weergeven in de tegels',
    displayDescription: 'Beschrijving inzending weergeven',
    displayDocuments: 'Geüploade documenten weergeven',
    displayEditLink: 'Aanpas-link weergeven voor moderators',
    displayLabel: 'Label weergeven',
    displayLikeButton: 'Like button weergeven in de dialog',
    displayLocationFilter: 'Locatie filter weergeven',
    displayMap: 'Kaart weergeven',
    displayOverviewTagGroups: 'Tags tonen in de tegels in het overzicht',
    displayPagination: 'Paginering tonen',
    displayRanking: 'Ranking weergeven',
    displaySearch: 'Zoekveld weergeven',
    displaySearchText: 'Zoektekst weergeven',
    displayShareButtons: 'Deel knoppen weergeven',
    displaySorting: 'Sorteeropties weergeven',
    displayStatusLabel: 'Status label weergeven',
    displaySummary: 'Samenvatting weergeven',
    displayTagFilters: 'Filteren op tags weergeven?',
    displayTagIcon: 'Tag icoon weergeven in de tegels',
    displayTags: 'Tags in dialog weergeven',
    displayTitle: 'Titel inzending weergeven',
    displayType: 'Weergavetype',
    displayUser: 'Gebruikersnaam weergeven in de tegels',
    displayVariant: 'Weergave versie',
    displayVote: 'Hoeveelheid stemmen weergeven',
    documentsDesc:
      'Welke beschrijving moet er boven de download knop(pen) komen?',
    documentsTitle: 'Welke titel moet er boven de download knop(pen) komen?',
    filterBehavior: 'Kies hoe je filter-tags combineert',
    filterBehaviorInclude:
      'Kies hoe de geselecteerde tags gecombineerd moeten worden met tags van andere types',
    headingLevel: 'Heading Level',
    includeOrExcludeStatusIds:
      'Toon inzendingen gekoppeld aan onderstaande statussen',
    includeOrExcludeTagIds: 'Toon inzendingen gekoppeld aan onderstaande tags',
    itemLink: 'Link (relatief) naar de specifieke inzending',
    itemsPerPage: 'Hoeveelheid items per pagina',
    listTabTitle: 'Titel van de lijst tab',
    mapTabTitle: 'Titel van de map tab',
    onlyIncludeStatusIds: 'Toon alleen inzendingen met deze statussen',
    onlyIncludeTagIds: 'Toon alleen inzendingen met deze tags',
    onlyShowTheseTagIds: 'Toon alleen deze tags',
    overviewTagGroups:
      'Selecteer van welke tag groepen de tags getoond moeten worden in de tegels',
    rawInput: 'Template voor display: " Creëer je eigen template."',
    resetText: 'Tekst voor het resetten van de filters',
    resourceType: 'Soort inzending',
    searchPlaceholder: 'Tekst voor zoekveld placeholder',
    showActiveTags:
      'Wil je onder de filters de actieve tags zien waar op is gefilterd?',
    sorting: 'Selecteer uw gewenste sorteeropties',
    summaryMaxLength:
      'Hoeveelheid karakters van de samenvatting die getoond wordt',
    tagGroups: 'Selecteer de gewenste tag groepen',
    textActiveSearch: 'Tekst voor actieve resultaten',
    titleMaxLength: 'Hoeveelheid karakters van de titel die getoond wordt',
  },
  resourcesmap: {
    buttonText: 'Knoptekst',
    color: 'Kleur',
    customUrl: 'Aangepaste URL',
    enableOnOffSwitching:
      'Wil je dat het mogelijk is om de kaartlagen aan en uit te zetten?',
    height: 'Hoogte',
    icon: 'Icoon',
    interactionType: 'Hoe wil je dat de interactie werkt met de polygonen?',
    label: 'Label',
    mapCenterMode: 'Automatisch inzoomen en centreren',
    markerInteractionType: 'Hoe wil je dat de interactie werkt met de markers?',
    openInNewTab: 'Open in nieuw tabblad',
    tilesVariant: 'Kaart stijl',
    width: 'Breedte',
  },
  videoSlider: {
    afterSubmitUrl: 'Url voor redirecten na opslaan (optioneel)',
    confirmationAdmin:
      'Krijgt de beheerder een bevestiging per mail bij een nieuwe inzending?',
    confirmationUser:
      'Krijgt de gebruiker een bevestiging per mail van zijn inzending?',
    defaultValue: 'Standaard aangevinkt?',
    description: 'Beschrijving',
    displayDescription: 'Enquête beschrijving weergeven',
    displayTitle: 'Enquête titel weergeven',
    fieldKey: 'Key voor het opslaan',
    fieldRequired: 'Is dit veld verplicht?',
    finalSlideDescription: 'Bevestiging -- beschrijving',
    finalSlideTitle: 'Bevestiging -- titel',
    formVisibility: 'Voor wie is de enquête zichtbaar?',
    group: 'Groeperen',
    hideLabel: 'Titel verbergen?',
    imageAlt: 'Afbeelding beschrijving voor screenreaders',
    imageDescription: 'Beschrijving afbeelding',
    isOtherOption: "Is 'Anders, namelijk...'",
    key: 'Optie tekst',
    maxCharacters: 'Maximaal aantal tekens',
    maxChoices: 'Maximaal te selecteren opties',
    maxChoicesMessage: 'Maximaal aantal bereikt melding',
    minCharacters: 'Minimaal aantal tekens',
    multiple: 'Mogen er meerdere afbeeldingen tegelijkertijd geüpload worden?',
    overwriteEmailAddress:
      'Overschrijf het e-mailadres waar de bevesting naartoe wordt gestuurd',
    placeholder: 'Placeholder',
    questionType: 'Type antwoorden',
    showSmileys: 'Wil je smileys tonen in plaats van een schaal?',
    title: 'Titel/Vraag',
    userEmailAddress:
      'Welk veld moet er worden gebruikt voor de bevestiging naar de gebruiker',
    variant: 'Is het veld qua grootte 1 regel of een tekstvak?',
    videoUrl: 'Video Url',
    view: 'Weergave',
  },
};
