const path = require('path');
const fs = require('fs');
const vm = require('vm');

/**
 * Read plugins.json and return enabled plugin entries.
 */
function getEnabledPlugins() {
  let dir = __dirname;
  while (dir !== path.dirname(dir)) {
    const candidate = path.join(dir, 'plugins.json');
    if (fs.existsSync(candidate)) {
      try {
        const config = JSON.parse(fs.readFileSync(candidate, 'utf-8'));
        return (config.plugins || []).filter((p) => p.enabled);
      } catch {
        return [];
      }
    }
    dir = path.dirname(dir);
  }
  return [];
}

/**
 * Load a plugin's manifest by evaluating its main file in a sandbox.
 * Only console is exposed — no process/require to limit what plugin
 * code can do during manifest evaluation.
 */
function loadManifest(packageName) {
  const searchDirs = [
    path.join(__dirname, 'node_modules'),
    path.resolve(__dirname, '../../node_modules'),
  ];

  for (const searchDir of searchDirs) {
    const pkgJsonPath = path.join(searchDir, packageName, 'package.json');
    if (!fs.existsSync(pkgJsonPath)) continue;

    try {
      const pkgJson = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf-8'));
      const mainFile = pkgJson.main || 'index.js';
      const mainPath = path.resolve(path.dirname(pkgJsonPath), mainFile);
      if (!fs.existsSync(mainPath)) continue;

      const code = fs.readFileSync(mainPath, 'utf-8');
      const moduleObj = { exports: {} };
      const sandbox = {
        module: moduleObj,
        exports: moduleObj.exports,
        require: () => ({}),
        __dirname: path.dirname(mainPath),
        __filename: mainPath,
        console,
      };
      vm.runInNewContext(code, sandbox, { filename: mainPath });
      return moduleObj.exports;
    } catch (err) {
      console.error(
        `[next.config] Failed to load manifest for "${packageName}":`,
        err.message
      );
    }
  }
  return null;
}

/**
 * Generate src/lib/generated-plugin-registry.ts with static dynamic imports
 * so webpack can bundle plugin components for both server and client.
 */
function generatePluginRegistry(plugins) {
  const componentEntries = [];
  const metaEntries = [];
  const menuItems = [];

  for (const plugin of plugins) {
    const packageName = plugin.packageName || plugin.package;
    if (!packageName) continue;

    const manifest = loadManifest(packageName);
    if (!manifest) continue;

    const pluginName = manifest.name || packageName;

    // Admin pages — collect both component imports and metadata in one pass
    if (manifest.admin?.pages) {
      for (const page of manifest.admin.pages) {
        if (!page.path) continue;

        if (page.componentPath) {
          const importPath = `${packageName}/${page.componentPath.replace(/^\.\//, '')}`;
          componentEntries.push({ key: page.path, importPath });
        }

        let pageHeader =
          pluginName.charAt(0).toUpperCase() + pluginName.slice(1);
        if (manifest.admin?.menuItems) {
          const menuItem = manifest.admin.menuItems.find(
            (m) => m.href === `/${page.path}`
          );
          if (menuItem) pageHeader = menuItem.label;
        }

        metaEntries.push({
          key: `__meta:${page.path}`,
          meta: { pluginName, packageName, pageHeader, pagePath: page.path },
        });
      }
    }

    // Widget admin components
    if (manifest.widgets) {
      for (const [widgetKey, widgetDef] of Object.entries(manifest.widgets)) {
        if (!widgetDef.adminComponentPath) continue;
        const importPath = `${packageName}/${widgetDef.adminComponentPath.replace(/^\.\//, '')}`;
        componentEntries.push({ key: `widget:${widgetKey}`, importPath });
      }
    }

    // Menu items
    if (manifest.admin?.menuItems) {
      menuItems.push(...manifest.admin.menuItems);
    }
  }

  // Build the generated file content
  const dynamicImports = componentEntries
    .map(
      (e) =>
        `  '${e.key}': dynamic(() => import('${e.importPath}'), { ssr: false }),`
    )
    .join('\n');

  const metaLines = metaEntries
    .map((e) => `  '${e.key}': ${JSON.stringify(e.meta)},`)
    .join('\n');

  const content = `// AUTO-GENERATED by next.config.js — DO NOT EDIT
import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

type PluginPageMeta = {
  pluginName: string;
  packageName: string;
  pageHeader: string;
  pagePath: string;
};

const components: Record<string, ComponentType<any>> = {
${dynamicImports}
};

const pageMeta: Record<string, PluginPageMeta> = {
${metaLines}
};

export const menuItems = ${JSON.stringify(menuItems, null, 2)} as const;

export function getPluginComponent(key: string): ComponentType<any> | undefined {
  return components[key];
}

export function getPluginPageMeta(requestPath: string): PluginPageMeta | undefined {
  return pageMeta[\`__meta:\${requestPath}\`];
}
`;

  const outPath = path.join(__dirname, 'src/lib/generated-plugin-registry.ts');
  const existing = fs.existsSync(outPath)
    ? fs.readFileSync(outPath, 'utf-8')
    : '';

  if (existing !== content) {
    fs.writeFileSync(outPath, content, 'utf-8');
    console.log(
      `[next.config] Generated plugin registry with ${componentEntries.length} component(s)`
    );
  }
}

const enabledPlugins = getEnabledPlugins();
const pluginPackageNames = enabledPlugins
  .map((p) => p.packageName || p.package)
  .filter(Boolean);

generatePluginRegistry(enabledPlugins);

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ['@openstad-headless/*', ...pluginPackageNames],
  serverExternalPackages: [
    '@openstad-headless/plugin-loader',
    ...pluginPackageNames,
  ],
  images: { domains: ['localhost', 'localhost:31470'] },
  async rewrites() {
    return [
      {
        source: '/health',
        destination: '/api/health',
      },
    ];
  },
  webpack(config, { isServer }) {
    // Resolve @openstad-headless packages from the monorepo packages dir,
    // which is mounted at ../../packages in both local dev and Docker.
    config.resolve.alias['@openstad-headless/plugin-loader'] = path.resolve(
      __dirname,
      '../../packages/plugin-loader'
    );

    // Ensure plugin packages can resolve react/next from admin-server's node_modules.
    // Plugins are transpiled in-place but don't have their own react installation.
    config.resolve.modules = [
      path.resolve(__dirname, 'node_modules'),
      'node_modules',
      ...(config.resolve.modules || []),
    ];

    // Keep the plugin-loader and plugin packages as native Node requires on the
    // server so that the loader's dynamic require(packageName) works correctly.
    if (isServer) {
      config.externals = config.externals || [];
      config.externals.push(
        '@openstad-headless/plugin-loader',
        ...pluginPackageNames
      );
    }

    return config;
  },
};

module.exports = nextConfig;
