---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-data-claim
  namespace: {{ .Release.Namespace }}
{{- if (.Values.persistence.annotations)}}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end}}
spec:
{{- if (and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
  {{- if (and .Values.persistence .Values.persistence.image .Values.persistence.image.size) }}
      storage: {{ .Values.persistence.image.size | default "1Gi" }}
  {{- else}}
      storage: 1Gi
  {{- end}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-data-claim
  namespace: {{ .Release.Namespace }}
{{- if (.Values.persistence.annotations)}}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end}}
spec:
{{- if (and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
  {{- if (and .Values.persistence .Values.persistence.docs .Values.persistence.docs.size) }}
      storage: {{ .Values.persistence.docs.size | default "1Gi" }}
  {{- else}}
      storage: 1Gi
  {{- end}}
{{- if ne .Values.cms.useS3 "true" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-data-claim
  namespace: {{ .Release.Namespace }}
{{- if (.Values.persistence.annotations)}}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end}}
spec:
{{- if (and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
  {{- if (and .Values.persistence .Values.persistence.cms .Values.persistence.cms.size) }}
      storage: {{ .Values.persistence.cms.size | default "1Gi" }}
  {{- else}}
      storage: 1Gi
  {{- end}}
{{- end}}
