export const defaultFormValues = [
    {
        "trigger": "1",
        "title": "Titel plan",
        "description": "Geef je voorstel een duidelijke titel, zodat anderen jouw inzending makkelijk kunnen vinden en direct snappen waar het over gaat.",
        "type": "title",
        "fieldKey": "title",
        "fieldRequired": true,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "options": [],
        "fieldType": "text"
    },
    {
        "trigger": "2",
        "title": "Samenvatting",
        "description": "Vertel in het kort iets meer over je plan.",
        "type": "summary",
        "fieldKey": "summary",
        "fieldRequired": true,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "textarea",
        "multiple": true,
        "options": [],
        "fieldType": "text"
    },
    {
        "trigger": "3",
        "title": "Beschrijving",
        "description": "Gebruik de ruimte hieronder om je voorstel verder uit te leggen.",
        "type": "description",
        "fieldKey": "description",
        "fieldRequired": true,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "textarea",
        "multiple": true,
        "options": [],
        "fieldType": "text"
    },
    {
        "trigger": "4",
        "title": "Plaatjes",
        "description": "Let op: Stuur alleen een foto mee die je zelf gemaakt hebt! Foto's van anderen kunnen auteursrechtelijk beschermd zijn. Je hebt toestemming nodig van de fotograaf om die foto te uploaden.",
        "type": "images",
        "fieldKey": "images",
        "fieldRequired": false,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "options": [],
        "allowedTypes": ['image/*'],
        "fieldType": "upload"
    },
    {
        "trigger": "5",
        "title": "Thema",
        "description": "Selecteer het thema waarop jouw plan betrekking heeft.",
        "type": "tags",
        "fieldKey": "tags[theme]",
        "fieldRequired": false,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "tags": 'theme',
        "fieldType": "select"
    },
    {
        "trigger": "6",
        "title": "Locatie",
        "description": "Heeft jouw plan betrekking op een specifieke plek? Klik dan op de juiste locatie in de kaart om een vlaggetje te plaatsen. Verwijder het vlaggetje door hem nogmaals aan te klikken.",
        "type": "location",
        "fieldKey": "location",
        "fieldRequired": false,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "options": [],
        "fieldType": "map"
    },
    {
        "trigger": "9",
        "title": "Inschatting kosten",
        "description": "Geef een inschatting van wat jouw plan kost. Vind je dit moeilijk, dan kun je ook het stadsdeel vragen om je daarbij te helpen. Als andere organisaties willen meebetalen aan het plan, kun je dat ook hier aangeven.",
        "type": "estimate",
        "fieldType": "text",
        "fieldKey": "estimate",
        "fieldRequired": false,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "options": []
    },
    {
        "trigger": "10",
        "title": "Welke rol ga je zelf vervullen bij de uitvoering?",
        "description": "Bewoners kunnen zelf of samen met de gemeente of een andere organisatie een plan uitvoeren. Geef aan welke rol je hierin wilt en kunt vervullen.",
        "type": "role",
        "fieldKey": "role",
        "fieldRequired": false,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "options": [],
        "fieldType": "text"
    },
    {
        "trigger": "11",
        "title": "Telefoonnummer (optioneel)",
        "description": "Vul hier (optioneel) je telefoonnummer in, zodat we snel contact met je kunnen opnemen over je plan.",
        "type": "phone",
        "fieldKey": "phone",
        "fieldRequired": false,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "options": [],
        "fieldType": "text"
    },
    {
        "trigger": "12",
        "title": "Tip",
        "description": "Geef een tip.",
        "type": "advice",
        "fieldKey": "advice",
        "fieldRequired": false,
        "onlyForModerator": false,
        "minCharacters": "",
        "maxCharacters": "",
        "variant": "text input",
        "multiple": true,
        "options": [],
        "fieldType": "text"
    }
]