#!/bin/bash

mysql -u root -p$MYSQL_ROOT_PASSWORD --execute \
"CREATE DATABASE IF NOT EXISTS \`$AUTH_DB_NAME\`;
CREATE DATABASE IF NOT EXISTS \`$IMAGE_DB_NAME\`;
CREATE DATABASE IF NOT EXISTS \`$API_DB_NAME\`;
GRANT ALL ON *.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;"